version: 2
updates:
  - package-ecosystem: "gomod"    
    directory: "/daemon"                
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"      
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(deps):"
    groups:
      github-actions:
        patterns:
          - "*"
