version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/daemon"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    commit-message:
      prefix: "chore(daemon):"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dev"
    commit-message:
      prefix: "ci:"
    groups:
      github-actions:
        patterns:
          - "*"
