# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 14

# Only issues or pull requests with all of these labels are check if stale. Defaults to `[]` (disabled)
onlyLabels:
  - "more info requested"

# Issues with these labels will never be considered stale
exemptLabels:[]

# Label to use when marking an issue as stale
staleLabel: stale

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. We appreciate your contributions, and we understand 
  things get busy.  This issue will be closed after 14 days if no 
  further activity occurs, but can always be reopened at a later date. 
  Thank you for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been automatically closed because it has not had
  recent activity, but it can be reopened.
  Thank you for your contributions.
