//
// Copyright 2020 New Relic Corporation. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// automatically generated by the FlatBuffers compiler, do not modify

package protocol

const (
	AppStatusUnknown        = 0
	AppStatusDisconnected   = 1
	AppStatusInvalidLicense = 2
	AppStatusConnected      = 3
	AppStatusStillValid     = 4
)

var EnumNamesAppStatus = map[int]string{
	AppStatusUnknown:        "Unknown",
	AppStatusDisconnected:   "Disconnected",
	AppStatusInvalidLicense: "InvalidLicense",
	AppStatusConnected:      "Connected",
	AppStatusStillValid:     "StillValid",
}
