//
// Copyright 2020 New Relic Corporation. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// automatically generated by the FlatBuffers compiler, do not modify

package protocol

const (
	MessageBodyNONE        = 0
	MessageBodyApp         = 1
	MessageBodyAppReply    = 2
	MessageBodyTransaction = 3
	MessageBodySpanBatch   = 4
)

var EnumNamesMessageBody = map[int]string{
	MessageBodyNONE:        "NONE",
	MessageBodyApp:         "App",
	MessageBodyAppReply:    "AppReply",
	MessageBodyTransaction: "Transaction",
	MessageBodySpanBatch:   "SpanBatch",
}
