//
// Copyright 2020 New Relic Corporation. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SpanBatch struct {
	_tab flatbuffers.Table
}

func GetRootAsSpanBatch(buf []byte, offset flatbuffers.UOffsetT) *SpanBatch {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SpanBatch{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSpanBatch(buf []byte, offset flatbuffers.UOffsetT) *SpanBatch {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SpanBatch{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SpanBatch) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SpanBatch) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SpanBatch) Count() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SpanBatch) MutateCount(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *SpanBatch) Encoded(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *SpanBatch) EncodedLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SpanBatch) EncodedBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SpanBatch) MutateEncoded(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func SpanBatchStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SpanBatchAddCount(builder *flatbuffers.Builder, count uint64) {
	builder.PrependUint64Slot(0, count, 0)
}
func SpanBatchAddEncoded(builder *flatbuffers.Builder, encoded flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(encoded), 0)
}
func SpanBatchStartEncodedVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func SpanBatchEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
