#
# Copyright 2021 New Relic Corporation. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

# Pull base image.
FROM redis

COPY /files/redis.conf /etc/redis/redis.conf
RUN chmod 777 /etc/redis/redis.conf

# Define mountable directories.
VOLUME ["/data"]

# Define working directory.
WORKDIR /data

# Define default command.
CMD ["redis-server", "/etc/redis/redis.conf"]

# Expose ports.
EXPOSE 6379
