//
// Copyright 2020 New Relic Corporation. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type AppStatus int8

const (
	AppStatusUnknown        AppStatus = 0
	AppStatusDisconnected   AppStatus = 1
	AppStatusInvalidLicense AppStatus = 2
	AppStatusConnected      AppStatus = 3
	AppStatusStillValid     AppStatus = 4
)

var EnumNamesAppStatus = map[AppStatus]string{
	AppStatusUnknown:        "Unknown",
	AppStatusDisconnected:   "Disconnected",
	AppStatusInvalidLicense: "InvalidLicense",
	AppStatusConnected:      "Connected",
	AppStatusStillValid:     "StillValid",
}

var EnumValuesAppStatus = map[string]AppStatus{
	"Unknown":        AppStatusUnknown,
	"Disconnected":   AppStatusDisconnected,
	"InvalidLicense": AppStatusInvalidLicense,
	"Connected":      AppStatusConnected,
	"StillValid":     AppStatusStillValid,
}

func (v AppStatus) String() string {
	if s, ok := EnumNamesAppStatus[v]; ok {
		return s
	}
	return "AppStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
