<?php
/*
 * Copyright 2020 New Relic Corporation. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

/*DESCRIPTION
Verify agent will ignore environment variables for config when
instructed to using NEW_RELIC_DISABLE_ENVVAR_CONFIG
*/


/*ENVIRONMENT
NEW_RELIC_DISABLE_ENVVAR_CONFIG=1
NEW_RELIC_ALLOW_RAW_EXCEPTION_MESSAGES=0
NEW_RELIC_ANALYTICS_EVENTS_CAPTURE_ATTRIBUTES=0
NEW_RELIC_ANALYTICS_EVENTS_ENABLED=0
NEW_RELIC_APPLICATION_LOGGING_ENABLED=0
NEW_RELIC_APPLICATION_LOGGING_FORWARDING_CONTEXT_DATA_ENABLED=1
NEW_RELIC_APPLICATION_LOGGING_FORWARDING_CONTEXT_DATA_EXCLUDE=exclude
NEW_RELIC_APPLICATION_LOGGING_FORWARDING_CONTEXT_DATA_INCLUDE=include
NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED=0
NEW_RELIC_APPLICATION_LOGGING_FORWARDING_LOG_LEVEL=verbosedebug
NEW_RELIC_APPLICATION_LOGGING_FORWARDING_MAX_SAMPLES_STORED=10
NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED=1
NEW_RELIC_APPLICATION_LOGGING_METRICS_ENABLED=0
NEW_RELIC_ATTRIBUTES_ENABLED=0
NEW_RELIC_ATTRIBUTES_EXCLUDE=exclude
NEW_RELIC_ATTRIBUTES_INCLUDE=include
NEW_RELIC_BROWSER_MONITORING_ATTRIBUTES_ENABLED=1
NEW_RELIC_BROWSER_MONITORING_ATTRIBUTES_EXCLUDE=exclude
NEW_RELIC_BROWSER_MONITORING_ATTRIBUTES_INCLUDE=include
NEW_RELIC_BROWSER_MONITORING_AUTO_INSTRUMENT=0
NEW_RELIC_BROWSER_MONITORING_CAPTURE_ATTRIBUTES=1
NEW_RELIC_BROWSER_MONITORING_DEBUG=1
NEW_RELIC_BROWSER_MONITORING_LOADER=good
NEW_RELIC_CAPTURE_PARAMS=1
NEW_RELIC_CODE_LEVEL_METRICS_ENABLED=0
NEW_RELIC_CROSS_APPLICATION_TRACER_ENABLED=1
NEW_RELIC_CUSTOM_EVENTS_MAX_SAMPLES_STORED=10
NEW_RELIC_CUSTOM_INSIGHTS_EVENTS_ENABLED=0
NEW_RELIC_CUSTOM_PARAMETERS_ENABLED=0
NEW_RELIC_DAEMON_ADDRESS=http://server.com
NEW_RELIC_DAEMON_APP_CONNECT_TIMEOUT=10000
NEW_RELIC_DAEMON_APP_TIMEOUT=10000
NEW_RELIC_DAEMON_AUDITLOG=audit
NEW_RELIC_DAEMON_COLLECTOR_HOST=collector
NEW_RELIC_DAEMON_LOCATION=/usr/local/bin/thedaemon
NEW_RELIC_DAEMON_LOGFILE=/tmp/daemon.log
NEW_RELIC_DAEMON_LOGLEVEL=verbose
NEW_RELIC_DAEMON_PIDFILE=/tmp/daemonpidfile.log
NEW_RELIC_DAEMON_PROXY=http://proxy.com
NEW_RELIC_DAEMON_SPECIAL_CURL_VERBOSE=on
NEW_RELIC_DAEMON_SPECIAL_INTEGRATION=on
NEW_RELIC_DAEMON_SSL_CA_BUNDLE=ssl_ca_dundle
NEW_RELIC_DAEMON_SSL_CA_PATH=ssl_ca_path
NEW_RELIC_DAEMON_START_TIMEOUT=1234
NEW_RELIC_DAEMON_UTILIZATION_DETECT_AWS=0
NEW_RELIC_DAEMON_UTILIZATION_DETECT_AZURE=0
NEW_RELIC_DAEMON_UTILIZATION_DETECT_DOCKER=0
NEW_RELIC_DAEMON_UTILIZATION_DETECT_GCP=0
NEW_RELIC_DAEMON_UTILIZATION_DETECT_KUBERNETES=0
NEW_RELIC_DAEMON_UTILIZATION_DETECT_PCF=0
NEW_RELIC_DAEMON_DONT_LAUNCH
NEW_RELIC_DATASTORE_TRACER_DATABASE_NAME_REPORTING_ENABLED=0
NEW_RELIC_DATASTORE_TRACER_INSTANCE_REPORTING_ENABLED=0
NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=0
NEW_RELIC_DISTRIBUTED_TRACING_EXCLUDE_NEWRELIC_HEADER=1
NEW_RELIC_ERROR_COLLECTOR_ATTRIBUTES_ENABLED=0
NEW_RELIC_ERROR_COLLECTOR_ATTRIBUTES_EXCLUDE=exclude
NEW_RELIC_ERROR_COLLECTOR_ATTRIBUTES_INCLUDE=include
NEW_RELIC_ERROR_COLLECTOR_CAPTURE_ATTRIBUTES=0
NEW_RELIC_ERROR_COLLECTOR_CAPTURE_EVENTS=0
NEW_RELIC_ERROR_COLLECTOR_ENABLED=0
NEW_RELIC_ERROR_COLLECTOR_IGNORE_ERRORS=on
NEW_RELIC_ERROR_COLLECTOR_IGNORE_EXCEPTIONS=on
NEW_RELIC_ERROR_COLLECTOR_IGNORE_USER_EXCEPTION_HANDLER=on
NEW_RELIC_ERROR_COLLECTOR_PRIORITIZE_API_ERRORS=1
NEW_RELIC_ERROR_COLLECTOR_RECORD_DATABASE_ERRORS=off
NEW_RELIC_FEATURE_FLAG=feature
NEW_RELIC_FRAMEWORK=drupal
NEW_RELIC_FRAMEWORK_DRUPAL_MODULES=0
NEW_RELIC_FRAMEWORK_WORDPRESS_HOOKS=0
NEW_RELIC_FRAMEWORK_WORDPRESS_HOOKS_OPTIONS=threshold
NEW_RELIC_FRAMEWORK_WORDPRESS_HOOKS_THRESHOLD=0
NEW_RELIC_FRAMEWORK_WORDPRESS_HOOKS_SKIP_FILENAME=1
NEW_RELIC_GUZZLE_ENABLED=0
NEW_RELIC_HIGH_SECURITY=1
NEW_RELIC_INFINITE_TRACING_SPAN_EVENTS_AGENT_QUEUE_SIZE=1234
NEW_RELIC_INFINITE_TRACING_SPAN_EVENTS_AGENT_QUEUE_TIMEOUT=1234
NEW_RELIC_INFINITE_TRACING_SPAN_EVENTS_QUEUE_SIZE=1234
NEW_RELIC_INFINITE_TRACING_TRACE_OBSERVER_HOST=observer
NEW_RELIC_INFINITE_TRACING_TRACE_OBSERVER_PORT=1234
NEW_RELIC_IGNORED_PARAMS=ignored
NEW_RELIC_LABELS=labels
NEW_RELIC_LOGFILE=new_php_agent.log
NEW_RELIC_LOGLEVEL=verbosedebug
NEW_RELIC_PHPUNIT_EVENTS_ENABLED=off
NEW_RELIC_PRELOAD_FRAMEWORK_LIBRARY_DETECTION=off
NEW_RELIC_PROCESS_HOST_DISPLAY_NAME=hostname
NEW_RELIC_SECURITY_POLICIES_TOKEN=1
NEW_RELIC_SPAN_EVENTS_ATTRIBUTES_ENABLED=0
NEW_RELIC_SPAN_EVENTS_ATTRIBUTES_EXCLUDE=exclude
NEW_RELIC_SPAN_EVENTS_ATTRIBUTES_INCLUDE=include
NEW_RELIC_SPAN_EVENTS_MAX_SAMPLES_STORED=10
NEW_RELIC_SPAN_EVENTS_ENABLED=0
NEW_RELIC_SPECIAL=special
NEW_RELIC_SPECIAL_APPINFO_TIMEOUT=1234
NEW_RELIC_SPECIAL_DISABLE_INSTRUMENTATION=1
NEW_RELIC_SPECIAL_ENABLE_EXTENSION_INSTRUMENTATION=1
NEW_RELIC_SPECIAL_EXPENSIVE_NODE_MIN=1
NEW_RELIC_SPECIAL_MAX_NESTING_LEVEL=10000
NEW_RELIC_SYNTHETICS_ENABLED=0
NEW_RELIC_TRANSACTION_EVENTS_ATTRIBUTES_ENABLED=0
NEW_RELIC_TRANSACTION_EVENTS_ATTRIBUTES_EXCLUDE=exclude
NEW_RELIC_TRANSACTION_EVENTS_ATTRIBUTES_INCLUDE=include
NEW_RELIC_TRANSACTION_EVENTS_ENABLED=0
NEW_RELIC_TRANSACTION_TRACER_ATTRIBUTES_ENABLED=0
NEW_RELIC_TRANSACTION_TRACER_ATTRIBUTES_EXCLUDE=exclude
NEW_RELIC_TRANSACTION_TRACER_ATTRIBUTES_INCLUDE=include
NEW_RELIC_TRANSACTION_TRACER_CAPTURE_ATTRIBUTES=0
NEW_RELIC_TRANSACTION_TRACER_CUSTOM=custom
NEW_RELIC_TRANSACTION_TRACER_DETAIL=0
NEW_RELIC_TRANSACTION_TRACER_ENABLED=0
NEW_RELIC_TRANSACTION_TRACER_EXPLAIN_ENABLED=0
NEW_RELIC_TRANSACTION_TRACER_EXPLAIN_THRESHOLD=1234
NEW_RELIC_TRANSACTION_TRACER_GATHER_INPUT_QUERIES=0
NEW_RELIC_TRANSACTION_TRACER_INTERNAL_FUNCTIONS_ENABLED=1
NEW_RELIC_TRANSACTION_TRACER_MAX_SEGMENTS_CLI=10
NEW_RELIC_TRANSACTION_TRACER_MAX_SEGMENTS_WEB=1234
NEW_RELIC_TRANSACTION_TRACER_RECORD_SQL=raw
NEW_RELIC_TRANSACTION_TRACER_SLOW_SQL=0
NEW_RELIC_TRANSACTION_TRACER_STACK_TRACE_THRESHOLD=10
NEW_RELIC_TRANSACTION_TRACER_THRESHOLD=10
NEW_RELIC_VULNERABILITY_MANAGEMENT_PACKAGE_DETECTION_ENABLED=0
NEW_RELIC_WEBTRANSACTION_NAME_FILES=0
NEW_RELIC_WEBTRANSACTION_NAME_FUNCTIONS=0
NEW_RELIC_WEBTRANSACTION_NAME_REMOVE_TRAILING_PATH=1
*/

/*EXPECT
*/

/*EXPECT_ANALYTICS_EVENTS
[
    "?? agent run id",
    {
        "reservoir_size": "??",
        "events_seen": 1
    },
    [
        [
            {
                "type": "Transaction",
                "name": "??",
                "timestamp": "??",
                "duration": "??",
                "totalTime": "??",
                "guid": "??",
                "sampled": true,
                "priority": "??",
                "traceId": "??",
                "error": false
            },
            {},
            {}
        ]
    ]
]
*/

/*EXPECT_CUSTOM_EVENTS
null
*/

/*EXPECT_ERROR_EVENTS
null
*/

/*EXPECT_LOG_EVENTS
null
*/

/*EXPECT_METRICS_EXIST
DurationByCaller/Unknown/Unknown/Unknown/Unknown/all
DurationByCaller/Unknown/Unknown/Unknown/Unknown/allOther
Supportability/Logging/Forwarding/PHP/enabled
Supportability/Logging/Metrics/PHP/enabled
Supportability/TxnData/CustomEvents
Supportability/TxnData/Metrics
Supportability/TxnData/Size
Supportability/TxnData/SlowSQL
*/

/*EXPECT_SPAN_EVENTS
[
    "?? agent run id",
    {
        "reservoir_size": "??",
        "events_seen": 1
    },
    [
        [
            {
                "category": "generic",
                "type": "Span",
                "guid": "??",
                "traceId": "??",
                "transactionId": "??",
                "name": "??",
                "timestamp": "??",
                "duration": "??",
                "priority": "??",
                "sampled": true,
                "nr.entryPoint": true,
                "transaction.name": "??"
            },
            {},
            {}
        ]
    ]
]
*/

/*EXPECT_TRACED_ERRORS
null
*/

/*EXPECT_TXN_TRACES
null
*/

/* list of INI entries to avoid */
$ignored_names = array(
    "newrelic.appname",              /* no harvest received if changed */
    "newrelic.daemon.port",          /* no harvest received if changed */
    "newrelic.enabled",              /* agent must be enabled for test to work */
    "newrelic.license",              /* necessary for integration_runner to contact collector */
);

/* get all names of ini and env var */
$names = newrelic_get_all_ini_envvar_names();

/* get current and global (should be the defaults since no INI files used) */
$ini_values =  ini_get_all();

/* verify each ini value is different than its default */
$err_str = "";
foreach ($names as $ini_name => $env_name) {
    if (in_array($ini_name, $ignored_names)) {
        continue;
    }

    $local_val = $ini_values[$ini_name]["local_value"];
    $global_val = $ini_values[$ini_name]["global_value"];

    /* also check the environment contains a setting for this ini value */
    $env_val = getenv($env_name);
    if (is_bool($env_val) && false == $env_val) {
        $err_str .= "     - the environment variable $env_name was not set for test as expected!\n";
    }

    if ($local_val != $global_val) {
        $err_str .= "     - $ini_name is different from default (uses $env_name):  current = '" . $local_val . "' default = '" . $global_val . "', env = " . $env_val . "\n";
    } else {
        //keep for debugging
        //$err_str .= "PASS   $ini_name not different from default (uses $env_name):  current = '" . $local_val . "' default = '" . $global_val . "', env = " . getenv($env_name) . "\n";
    }
}

if (0 != strlen($err_str)) {
    echo "The following environment variables were used for config even though" .
         "this feature was disabled!\n\n";
    echo $err_str . "\n";
}
