name: _get-php-versions

permissions: {}

on:
  workflow_call:
    inputs:
      arch:
        description: 'Target architecture (amd64, arm64)'
        required: true
        type: string
    outputs:
      php-versions:
        description: 'JSON array of supported PHP versions for the given architecture'
        value: ${{ jobs.get-php-versions.outputs.php-versions }}

jobs:
  get-php-versions:
    runs-on: ubuntu-latest
    outputs:
      php-versions: ${{ steps.get-php-versions.outputs.php-versions }}
    steps:
      - name: Checkout php_versions.mk
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          sparse-checkout: make/php_versions.mk
          path: php-agent
      - name: Get PHP versions
        id: get-php-versions
        env:
          ARCH: ${{ inputs.arch }}
        run: |
          json=$(make -f php-agent/make/php_versions.mk php-versions-json ARCH=$ARCH)
          echo "php-versions=$json" >> $GITHUB_OUTPUT
