#
# Copyright 2020 New Relic Corporation. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

#
# This is the workflow to do a release build.
#
name: release_CI

#
# Control when the action will run. 
#
on:
  #
  # Run this workflow manually from the Actions tab or using the API
  #
  workflow_dispatch:

jobs:
  agent_release:
    env:
      IMAGE_NAME: newrelic/nr-php-agent-builder
      IMAGE_VERSION: v1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [gnu, musl]
        php_ver: ['8.2']
        arch: [x64]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
          path: newrelic-php-agent
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: >
          docker run --rm --platform linux/${{matrix.arch}}
          -v "${GITHUB_WORKSPACE}/newrelic-php-agent":"/usr/local/src/newrelic-php-agent"
          -e OPTIMIZE=1
          $IMAGE_NAME:agent-builder-php${{matrix.php_ver}}-${{matrix.platform}}-$IMAGE_VERSION release-${{matrix.php_ver}}-gha
      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.php_ver }}binaries
          path: releases
          if-no-files-found: error
  combine:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Combine artifacts from matrix build
    needs: agent_release
    steps:
      - name: Create directory
        run: mkdir releases
      - name: Download to directory
        uses: actions/download-artifact@v2
        with:
          path: releases
      - run: sudo apt install tree
      - run: tree
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: $GITHUB_SHA
          path: releases
          if-no-files-found: error
