# Copyright 2020 New Relic Corporation. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

name: run-integration-tests
run-name: Testing ${{ inputs.origin }}:${{ inputs.ref }} (by @${{ github.actor }})

on:
  workflow_dispatch:
    inputs:
      origin:
        description: 'newrelic-php-agent origin'
        required: true
        default: 'newrelic' 
        type: string
      ref:
        description: 'Branch or tag'
        required: true
        default: 'dev' 
        type: string
      runner-type:
        description: 'Type of a runner to use for integration tests on arm64'
        required: true
        default: 'ubuntu-20.04-4core' 
        type: choice
        options: 
        - ubuntu-20.04-4core
        - ubuntu-20.04-8core
        - ubuntu-20.04-16core
        - ubuntu-22.04-4core
        - ubuntu-latest

jobs:
  build-test-runner-amd64:
    uses: ./.github/workflows/make-for-platform-on-arch.yml
    with:
      origin: ${{ inputs.origin }}
      ref: ${{ inputs.ref }}
      make-variant: go
      make-variant-version: ${{vars.MAKE_GO_VERSION}}
      make-target: bin/integration_runner
      artifact-name: integration_runner
      artifact-pattern: bin/integration_runner
      arch: amd64
      runs-on: ubuntu-latest
    secrets: inherit
  build-test-runner-arm64:
    uses: ./.github/workflows/make-for-platform-on-arch.yml
    with:
      origin: ${{ inputs.origin }}
      ref: ${{ inputs.ref }}
      make-variant: go
      make-variant-version: ${{vars.MAKE_GO_VERSION}}
      make-target: bin/integration_runner
      artifact-name: integration_runner
      artifact-pattern: bin/integration_runner
      arch: arm64
      runs-on: ubuntu-latest
    secrets: inherit

  build-agent-amd64:
    uses: ./.github/workflows/make-agent.yml
    with:
      origin: ${{ inputs.origin }}
      ref: ${{ inputs.ref }}
      arch: amd64
      runs-on: ubuntu-latest
    secrets: inherit
  build-agent-arm64:
    uses: ./.github/workflows/make-agent.yml
    with:
      origin: ${{ inputs.origin }}
      ref: ${{ inputs.ref }}
      arch: arm64
      runs-on: ubuntu-latest
    secrets: inherit

  test-amd64:
    needs: [build-test-runner-amd64, build-agent-amd64]
    uses: ./.github/workflows/make-integration-tests.yml
    with:
      origin: ${{ inputs.origin }}
      ref: ${{ inputs.ref }}
      arch: amd64
      runs-on: ubuntu-latest
      continue-on-error: false
    secrets: inherit
  test-arm64:
    needs: [build-test-runner-arm64, build-agent-arm64]
    uses: ./.github/workflows/make-integration-tests.yml
    with:
      origin: ${{ inputs.origin }}
      ref: ${{ inputs.ref }}
      arch: arm64
      runs-on: ${{inputs.runner-type}}
      continue-on-error: true
    secrets: inherit
